# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy multipostgres image to dockerhub'
  task prod: %w[dockerhub:registry:login
                rubylint
                image:docker:multipostgres
                dockerhub:registry:tag:latest
                dockerhub:registry:push:latest]
end
